import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";

import Providers from "@/components/providers";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("bg-slate-100", inter.className)}>
        <main className="py-4 w-full flex flex-col justify-center items-center">
          <Providers>
            <Navbar />
            {children}
            <Toaster richColors />
          </Providers>
        </main>
      </body>
    </html>
  );
}
